# Changes here will be overwritten by Copier
_commit: v0.1.0-29-g9f8fe8a
_src_path: https://github.com/navapbc/template-application-nextjs
app_enable_storybook_cd: true
app_local_port: 3000
app_name: app
