# Changes here will be overwritten by Copier
_commit: v0.14.0-76-g68a122d
_src_path: ../template-infra
base_code_repository_url: git@github.com:navapbc/platform-test-nextjs.git
base_default_region: us-east-1
base_owner: platform-admins
base_project_name: platform-nextjs
template: base
