# Changes here will be overwritten by Copier
_commit: v0.15.3-3-g5cc1f4d
_src_path: https://github.com/navapbc/template-infra
base_code_repository_url: git@github.com:navapbc/platform-test-nextjs.git
base_default_region: us-east-1
base_owner: platform-admins
base_project_name: platform-nextjs
template: base
