#!/bin/bash


# Print the environment variables to confirm
echo "Running tests with APP_NAME=${APP_NAME} and BASE_URL=${BASE_URL}"

echo "CI => ${CI}"

# Run the e2e tests
make e2e-test-native E2E_ARGS="--reporter=blob"



# Define the path to the blob-report directory
BLOB_REPORT_PATH="/e2e/blob-report"

# Set a timeout in seconds (e.g., 30 seconds)
TIMEOUT=120
WAIT_INTERVAL=2  # Interval between checks, in seconds

echo "Waiting for files to be created in the blob-report directory..."

# Start a timer
SECONDS=0

echo "Contents of $BLOB_REPORT_PATH before:"
ls -la "$BLOB_REPORT_PATH"

# Loop until the directory exists and contains files or timeout is reached
while [[ ! -d "$BLOB_REPORT_PATH" || -z "$(ls -A "$BLOB_REPORT_PATH")" ]]; do
  if [[ $SECONDS -ge $TIMEOUT ]]; then
    echo "Timeout reached. No files found in blob-report directory."
    exit 1
  fi
  sleep $WAIT_INTERVAL
done

echo "Files detected in the blob-report directory."

# List the contents of the blob-report directory
echo "Contents of $BLOB_REPORT_PATH after:"
ls -la "$BLOB_REPORT_PATH"

echo "contents of playwright-report"
ls -la ./e2e/playwright-report
