#!/bin/bash
#
# Script to run Playwright tests with a specified app name.
# Requires the APP_NAME and BASE_URL environment variables to be set.

# Ensure APP_NAME is provided
if [[ -z "${APP_NAME}" ]]; then
  echo "You must pass in a specific APP_NAME. IE: APP_NAME=app npm run e2e-test" >&2
  exit 1
fi

# Warn about optional BASE_URL usage
if [[ -z "${BASE_URL}" ]]; then
  echo "Warning: BASE_URL not specified. Using default configuration in playwright.config.js"
fi

npx playwright test --config "${APP_NAME}/playwright.config.js" "$@"
