name: Accessibility Scans

on:
  workflow_call:
    inputs:
      service_endpoint:
        required: true
        type: string

jobs:
  accessibility:
    name: Accessibility Scans
    runs-on: ubuntu-latest

    env:
      SERVICE_ENDPOINT_URL: ${{ inputs.service_endpoint }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache-dependency-path: ./app/package-lock.json
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./app

      - name: Create screenshots directory
        run: mkdir -p ./app/screenshots-output

      - name: Debug service endpoint
        run: echo "SERVICE_ENDPOINT_URL is set to $SERVICE_ENDPOINT_URL"

      - name: Update pa11y-ci config
        run: |
          jq ".urls = [\"${SERVICE_ENDPOINT_URL}\"]" ./app/.pa11yci-desktop.json > ./app/.pa11yci-desktop-temp.json
          mv ./app/.pa11yci-desktop-temp.json ./app/.pa11yci-desktop.json
          jq ".urls = [\"${SERVICE_ENDPOINT_URL}\"]" ./app/.pa11yci-mobile.json > ./app/.pa11yci-mobile-temp.json
          mv ./app/.pa11yci-mobile-temp.json ./app/.pa11yci-mobile.json

      - name: Cat updated pa11y-ci config for desktop
        run: cat ./app/.pa11yci-desktop.json

      - name: Cat updated pa11y-ci config for mobile
        run: cat ./app/.pa11yci-mobile.json

      - name: Run pa11y-ci
        run: |
          set -e # Ensure the script fails if any command fails
          npm run test:pa11y-desktop
          npm run test:pa11y-mobile
          echo "pa11y-ci tests finished."
        working-directory: ./app

      - name: Upload screenshots to artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./app/screenshots-output
