name: E2E Tests on Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-e2e-tests:
    name: Trigger E2E Tests on Main
    uses: ./.github/workflows/e2e-tests.yml
    with:
      service_endpoint: "http://app-dev-2093346449.us-east-1.elb.amazonaws.com"
      app_name: "app"
