name: E2E Tests

on:
  workflow_call:
    inputs:
      service_endpoint:
        required: true
        type: string
      app_name:
        required: false
        type: string

jobs:
  e2e:
    name: E2E Tests - Shard ${{ matrix.shard }} of ${{ matrix.total_shards }}
    runs-on: ubuntu-latest

    strategy:
        matrix:
          shard: [1, 2, 3]
          total_shards: [3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright browsers
        run: make e2e-setup-ci

      - name: Run e2e tests (Shard ${{ matrix.shard }}/${{ matrix.total_shards }})
        env:
          CI: true  # Ensure CI environment variable is set
          TOTAL_SHARDS: ${{ matrix.total_shards }}
          CURRENT_SHARD: ${{ matrix.shard }}
        run: make e2e-test APP_NAME=${{ inputs.app_name }} BASE_URL=${{ inputs.service_endpoint }}

      - name: Verify Blob Report Directory
        run: |
          echo "Contents of blob-report directory:"
          ls -R blob-report || echo "blob-report directory not found"

      - name: Upload Blob Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-blob-reports-shard-${{ matrix.shard }}
          path: blob-report
          retention-days: 1

  create-report:
    name: Create Merged Test Report
    if: always()
    needs: [e2e]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4


      - name: Install dependencies
        run: npm ci

      - name: Download All Blob Reports
        uses: actions/download-artifact@v4
        with:
          name: all-blob-reports-shard-*
          path: all-blob-reports

      - name: Merge Blob Reports into HTML
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload Merged HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: merged-html-report
          path: all-blob-reports/playwright-report
          retention-days: 7
