name: E2E Tests
run-name: E2E Tests

on:
  workflow_call:
    inputs:
      service_endpoint:
        required: true
        type: string
      app_name:
        required: false
        type: string

jobs:
  e2e:
    name: E2E Tests - Shard ${{ matrix.shard }} of ${{ matrix.total_shards }}
    runs-on: ubuntu-latest

    strategy:
        matrix:
          shard: [1, 2, 3]
          total_shards: [3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright browsers
        run: make e2e-setup-ci

      - name: Ensure permissions for blob-report directory
        run: |
          mkdir -p ./e2e/blob-report
          chmod -R 777 ./e2e/blob-report

      - name: Verify Blob Report Directory
        run: |
            echo "Contents of blob-report directory on host:"
            ls -R ./e2e/blob-report || echo "blob-report directory not found"

      - name: Run e2e tests (Shard ${{ matrix.shard }}/${{ matrix.total_shards }})
        run: |
          make e2e-test \
            APP_NAME=${{ inputs.app_name }} \
            BASE_URL=${{ inputs.service_endpoint }} \
            CURRENT_SHARD=${{ matrix.shard }} \
            TOTAL_SHARDS=${{ matrix.total_shards }}

      - name: Check blob-report contents inside container
        run: docker exec playwright-e2e-container ls -la /e2e/blob-report

      - name: Verify Blob Report Directory 2
        run: |
          echo "Contents of blob-report directory on host:"
          ls -R ./e2e/blob-report || echo "blob-report directory not found"

      - name: Upload Blob Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-blob-reports-shard-${{ matrix.shard }}
          path: ./e2e/blob-report
          retention-days: 1

  create-report:
    name: Create Merged Test Report
    needs: [e2e]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies in ./e2e
        run: make e2e-setup-ci

      - name: Download Blob Reports from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-blob-reports-shard-*
          path: ./e2e/all-blob-reports

      - name: Merge Blob Reports into HTML
        run: npx playwright merge-reports --reporter html ./all-blob-reports
        working-directory: ./e2e

      - name: Upload Merged HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: merged-html-report
          path: ./e2e/playwright-report
          retention-days: 7
