name: E2E Tests
run-name: E2E Tests

on:
  workflow_call:
    inputs:
      service_endpoint:
        required: true
        type: string
      app_name:
        required: false
        type: string

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Cache Playwright binaries
        uses: actions/cache@v3
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: make e2e-setup-ci

  e2e:
    name: E2E Tests - Shard ${{ matrix.shard }} of ${{ matrix.total_shards }}
    runs-on: ubuntu-latest
    needs: install

    strategy:
        matrix:
          shard: [1, 2, 3]
          total_shards: [3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Restore Playwright binaries from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}

      - name: Run e2e tests (Shard ${{ matrix.shard }}/${{ matrix.total_shards }})
        run: |
          make e2e-test \
            APP_NAME=${{ inputs.app_name }} \
            BASE_URL=${{ inputs.service_endpoint }} \
            CURRENT_SHARD=${{ matrix.shard }} \
            TOTAL_SHARDS=${{ matrix.total_shards }}

      - name: Verify blob report directory after tests
        run: |
          echo "Contents of blob-report directory on host:"
          ls -R ./e2e/blob-report || echo "blob-report directory not found"

      - name: Upload Blob Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: all-blob-reports-shard-${{ matrix.shard }}
          path: ./e2e/blob-report
          retention-days: 1

  create-report:
    name: Create Merged Test Report
    if: ${{ !cancelled() }}
    needs: [e2e]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: lts/*

      - name: Install dependencies in ./e2e
        run: make e2e-setup-ci

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: all-blob-reports-shard-*
          merge-multiple: true

      - name: Verify Downloaded Artifacts
        run: |
          echo "Contents of all-blob-reports after download:"
          ls -R all-blob-reports

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Verify Merged Report
        run: |
          echo "Contents of ./playwright-report after merge:"
          ls -R ./playwright-report || echo "No report found in ./playwright-report"

      - name: Upload Merged HTML Report
        uses: actions/upload-artifact@v4
        with:
            name: merged-html-report
            path: ./playwright-report
            retention-days: 7
