name: E2E Tests

on:
  workflow_call:
    inputs:
      service_endpoint:
        required: true
        type: string
      app_name:
        required: false
        type: string

jobs:
  e2e:
    name: " " # GitHub UI is noisy when calling reusable workflows, so use whitespace for name to reduce noise
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.48.1-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Since the Docker image includes dependencies, no need to set up Node.js or Playwright browsers
      - name: Install make
        run: apt-get update && apt-get install -y make


      - name: Run e2e tests
        run: make e2e-test APP_NAME=${{ inputs.app_name }} BASE_URL=${{ inputs.service_endpoint }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./e2e/playwright-report
