name: PR Environment Update

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      commit_hash:
        required: true
        type: string

jobs:
  build-and-publish:
    name: " "
    uses: ./.github/workflows/build-and-publish.yml
    with:
      app_name: ${{ inputs.app_name }}
      ref: ${{ inputs.commit_hash }}

  update:
    name: Update environment
    needs: [build-and-publish]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write # Needed to comment on PR

    concurrency: pr-environment-${{ inputs.pr_number }}

    outputs:
      service_endpoint: ${{ steps.set-output.outputs.service_endpoint }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: ${{ inputs.app_name }}
          environment: ${{ inputs.environment }}

      - name: Update environment
        id: update-environment
        run: ./bin/update-pr-environment "${{ inputs.app_name }}" "${{ inputs.environment }}" "${{ inputs.pr_number }}" "${{ inputs.commit_hash }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save service endpoint to file
        run: echo "${{ steps.update-environment.outputs.service_endpoint }}" > service_endpoint.txt

      - name: Debug service endpoint file content
        run: cat service_endpoint.txt

      - name: Set output
        id: set-output
        run: echo "service_endpoint=$(cat service_endpoint.txt)" >> "$GITHUB_OUTPUT"
        shell: bash

  accessibility:
    name: Accessibility Checks
    needs: update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache-dependency-path: ./app/package-lock.json
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./app

      - name: Create screenshots directory
        run: mkdir -p ./app/screenshots-output

      - name: Set service endpoint URL
        run: echo "SERVICE_ENDPOINT_URL=\"${{ needs.update.outputs.service_endpoint }}\"" >> "$GITHUB_ENV"
        shell: bash

      - name: Debug service endpoint
        run: echo "SERVICE_ENDPOINT_URL is set to $SERVICE_ENDPOINT_URL"

      - name: Update pa11y-ci config
        run: |
          jq ".urls = [\"${SERVICE_ENDPOINT_URL}\"]" ./app/.pa11yci-desktop.json > ./app/.pa11yci-desktop-temp.json
          mv ./app/.pa11yci-desktop-temp.json ./app/.pa11yci-desktop.json
          jq ".urls = [\"${SERVICE_ENDPOINT_URL}\"]" ./app/.pa11yci-mobile.json > ./app/.pa11yci-mobile-temp.json
          mv ./app/.pa11yci-mobile-temp.json ./app/.pa11yci-mobile.json

      - name: Cat updated pa11y-ci config for desktop
        run: cat ./app/.pa11yci-desktop.json

      - name: Cat updated pa11y-ci config for mobile
        run: cat ./app/.pa11yci-mobile.json

      - name: Run pa11y-ci
        run: |
          set -e # Ensure the script fails if any command fails
          npm run test:pa11y-desktop
          npm run test:pa11y-mobile
          echo "pa11y-ci tests finished."
        working-directory: ./app

      - name: Upload screenshots to artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./app/screenshots-output
